// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

export function CreateTunnel(name: string, host: string, port: number): $CancellablePromise<models$0.Tunnel | null> {
    return $Call.ByID(1709182411, name, host, port).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DeleteById(id: number): $CancellablePromise<void> {
    return $Call.ByID(13459786, id);
}

export function GetAllTunnels(): $CancellablePromise<models$0.Tunnel[]> {
    return $Call.ByID(460695761).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ToggleTunnel(id: number): $CancellablePromise<void> {
    return $Call.ByID(2540223067, id);
}

// Private type creation functions
const $$createType0 = models$0.Tunnel.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
