// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

export class Tunnel {
    "id": number;
    "name": string;
    "port": number;
    "host": string;
    "active": boolean;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new Tunnel instance. */
    constructor($$source: Partial<Tunnel> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("active" in $$source)) {
            this["active"] = false;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Tunnel instance from a string or object.
     */
    static createFrom($$source: any = {}): Tunnel {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Tunnel($$parsedSource as Partial<Tunnel>);
    }
}
